<?php
declare(strict_types=1);
if (!is_file(__DIR__.'/config.php')) { header('Location: install.php'); exit; }
require __DIR__.'/bootstrap.php';

if (isset($_GET['logout'])) { session_regenerate_id(true); $_SESSION=[]; header('Location: admin.php'); exit; }
$loginError='';
if (!admin_user() && $_SERVER['REQUEST_METHOD']==='POST' && isset($_POST['login'])) {
    verify_csrf();
    $attempts=(int)($_SESSION['login_attempts']??0);$last=(int)($_SESSION['login_last']??0);
    if($attempts>=8 && time()-$last<900){$loginError='Too many attempts. Try again in 15 minutes.';}else{
        $stmt=db()->prepare('SELECT id,name,email,password_hash,role FROM admins WHERE email=? LIMIT 1');$stmt->execute([strtolower(trim((string)$_POST['email']))]);$user=$stmt->fetch();
        if($user&&password_verify((string)$_POST['password'],$user['password_hash'])){unset($user['password_hash']);$_SESSION['admin']=$user;$_SESSION['login_attempts']=0;session_regenerate_id(true);db()->prepare('UPDATE admins SET last_login_at=NOW() WHERE id=?')->execute([$user['id']]);header('Location: admin.php');exit;}
        $_SESSION['login_attempts']=$attempts+1;$_SESSION['login_last']=time();$loginError='Incorrect email or password.';
    }
}
if (!admin_user()) { ?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>SLIID Admin Login</title><style>
:root{--n:#071c29;--g:#ac874b;--p:#f3f0e9}*{box-sizing:border-box}body{margin:0;background:var(--p);color:#172733;font:14px Arial;display:grid;min-height:100vh;place-items:center}.login{width:min(430px,calc(100% - 30px));background:#fff;padding:38px;box-shadow:0 25px 70px #071c2920;border-top:6px solid var(--g)}h1{font:44px Georgia;margin:0;color:var(--n)}p{color:#65717a}label{display:block;font-size:11px;font-weight:bold;text-transform:uppercase;letter-spacing:.08em;margin:18px 0 0}input{width:100%;padding:13px;margin-top:7px;border:1px solid #d3d0c8}button{width:100%;background:var(--g);color:#fff;border:0;padding:14px;margin-top:22px;font-weight:bold;text-transform:uppercase;letter-spacing:.12em}.error{background:#fee;color:#900;padding:10px;margin-top:15px}</style></head><body><form class="login" method="post"><h1>SLIID</h1><p>Administration portal</p><?php if($loginError):?><div class="error"><?=e($loginError)?></div><?php endif?><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="login" value="1"><label>Email<input type="email" name="email" autocomplete="username" required></label><label>Password<input type="password" name="password" autocomplete="current-password" required></label><button>Sign in →</button></form></body></html><?php exit; }

$section=preg_replace('/[^a-z-]/','',$_GET['section']??'dashboard');$allowed=['dashboard','members','news','events','publications','enquiries','applications','admins','audit'];if(!in_array($section,$allowed,true))$section='dashboard';
$notice='';$error='';
function go(string $section,string $message='Saved'):never{header('Location: admin.php?section='.$section.'&notice='.urlencode($message));exit;}
function is_super():bool{return (admin_user()['role']??'')==='super_admin';}

if($_SERVER['REQUEST_METHOD']==='POST'&&!isset($_POST['login'])){
    require_admin();verify_csrf();$action=$_POST['action']??'';
    try{
        if($action==='save_member'){
            $id=(int)($_POST['id']??0);$image=upload_file('image',['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp'],'images');$values=[trim($_POST['name']),trim($_POST['membership_number']),$_POST['category'],trim($_POST['email']),trim($_POST['phone']),trim($_POST['location']),trim($_POST['specialisations']),trim($_POST['bio']),trim($_POST['website']),isset($_POST['featured'])?1:0,$_POST['status']];
            if($id){$sql='UPDATE members SET name=?,membership_number=?,category=?,email=?,phone=?,location=?,specialisations=?,bio=?,website=?,featured=?,status=?'.($image?',image_path=?':'').' WHERE id=?';if($image)$values[]=$image;$values[]=$id;db()->prepare($sql)->execute($values);audit('update','member',$id);}else{$values[]=$image;$stmt=db()->prepare('INSERT INTO members(name,membership_number,category,email,phone,location,specialisations,bio,website,featured,status,image_path) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)');$stmt->execute($values);$id=(int)db()->lastInsertId();audit('create','member',$id);}go('members','Member saved.');
        }
        if($action==='save_news'){
            $id=(int)($_POST['id']??0);$image=upload_file('image',['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp'],'images');$slug=slugify($_POST['slug']?:$_POST['title']);$published=$_POST['status']==='published'?($_POST['published_at']?:date('Y-m-d H:i:s')):null;$values=[trim($_POST['title']),$slug,trim($_POST['excerpt']),trim($_POST['content']),trim($_POST['category']),$_POST['status'],$published];
            if($id){$sql='UPDATE news SET title=?,slug=?,excerpt=?,content=?,category=?,status=?,published_at=?'.($image?',image_path=?':'').' WHERE id=?';if($image)$values[]=$image;$values[]=$id;db()->prepare($sql)->execute($values);audit('update','news',$id);}else{$values[]=$image;db()->prepare('INSERT INTO news(title,slug,excerpt,content,category,status,published_at,image_path) VALUES(?,?,?,?,?,?,?,?)')->execute($values);$id=(int)db()->lastInsertId();audit('create','news',$id);}go('news','News item saved.');
        }
        if($action==='save_event'){
            $id=(int)($_POST['id']??0);$image=upload_file('image',['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp'],'images');$slug=slugify($_POST['slug']?:$_POST['title']);$values=[trim($_POST['title']),$slug,trim($_POST['summary']),trim($_POST['description']),trim($_POST['venue']),str_replace('T',' ',$_POST['starts_at']),$_POST['ends_at']?str_replace('T',' ',$_POST['ends_at']):null,trim($_POST['registration_url']),isset($_POST['featured'])?1:0,$_POST['status']];
            if($id){$sql='UPDATE events SET title=?,slug=?,summary=?,description=?,venue=?,starts_at=?,ends_at=?,registration_url=?,featured=?,status=?'.($image?',image_path=?':'').' WHERE id=?';if($image)$values[]=$image;$values[]=$id;db()->prepare($sql)->execute($values);audit('update','event',$id);}else{$values[]=$image;db()->prepare('INSERT INTO events(title,slug,summary,description,venue,starts_at,ends_at,registration_url,featured,status,image_path) VALUES(?,?,?,?,?,?,?,?,?,?,?)')->execute($values);$id=(int)db()->lastInsertId();audit('create','event',$id);}go('events','Event saved.');
        }
        if($action==='save_publication'){
            $id=(int)($_POST['id']??0);$file=upload_file('file',['application/pdf'=>'pdf'],'documents');$published=$_POST['status']==='published'?($_POST['published_at']?:date('Y-m-d H:i:s')):null;$values=[trim($_POST['title']),trim($_POST['description']),trim($_POST['category']),trim($_POST['external_url']),$_POST['status'],$published];
            if($id){$sql='UPDATE publications SET title=?,description=?,category=?,external_url=?,status=?,published_at=?'.($file?',file_path=?':'').' WHERE id=?';if($file)$values[]=$file;$values[]=$id;db()->prepare($sql)->execute($values);audit('update','publication',$id);}else{$values[]=$file;db()->prepare('INSERT INTO publications(title,description,category,external_url,status,published_at,file_path) VALUES(?,?,?,?,?,?,?)')->execute($values);$id=(int)db()->lastInsertId();audit('create','publication',$id);}go('publications','Publication saved.');
        }
        if($action==='set_status'){$table=$_POST['table']==='enquiries'?'enquiries':'membership_applications';$id=(int)$_POST['id'];$valid=$table==='enquiries'?['new','in_progress','resolved','spam']:['new','reviewing','approved','rejected'];$status=in_array($_POST['status'],$valid,true)?$_POST['status']:$valid[0];db()->prepare("UPDATE $table SET status=? WHERE id=?")->execute([$status,$id]);audit('status',$table,$id,['status'=>$status]);go($table==='enquiries'?'enquiries':'applications','Status updated.');}
        if($action==='delete'&&is_super()){$tables=['members'=>'member','news'=>'news','events'=>'event','publications'=>'publication'];$table=$_POST['table']??'';if(!isset($tables[$table]))throw new RuntimeException('Invalid item.');$id=(int)$_POST['id'];db()->prepare("DELETE FROM $table WHERE id=?")->execute([$id]);audit('delete',$tables[$table],$id);go($table,'Item deleted.');}
        if($action==='save_admin'&&is_super()){$email=strtolower(trim($_POST['email']));if(!filter_var($email,FILTER_VALIDATE_EMAIL)||strlen($_POST['password'])<12)throw new RuntimeException('Enter a valid email and a password of at least 12 characters.');db()->prepare('INSERT INTO admins(name,email,password_hash,role) VALUES(?,?,?,?)')->execute([trim($_POST['name']),$email,password_hash($_POST['password'],PASSWORD_DEFAULT),$_POST['role']==='super_admin'?'super_admin':'editor']);audit('create','admin',(int)db()->lastInsertId());go('admins','Administrator created.');}
    }catch(Throwable $e){$error=$e->getMessage();}
}
$notice=$_GET['notice']??$notice;
function rows(string $table,string $order='id DESC'):array{return db()->query("SELECT * FROM $table ORDER BY $order LIMIT 250")->fetchAll();}
function record(string $table,int $id):array{if(!$id)return[];$stmt=db()->prepare("SELECT * FROM $table WHERE id=?");$stmt->execute([$id]);return$stmt->fetch()?:[];}
$editId=(int)($_GET['edit']??0);
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e(ucfirst($section))?> | SLIID Admin</title><link rel="stylesheet" href="assets/admin.css"></head><body><aside class="sidebar"><a class="brand" href="admin.php"><b>SLIID</b><span>Administration</span></a><nav><?php foreach(['dashboard'=>'Overview','members'=>'Members','news'=>'News','events'=>'Events','publications'=>'Publications','enquiries'=>'Enquiries','applications'=>'Applications','admins'=>'Administrators','audit'=>'Audit log'] as $key=>$label):?><a class="<?=$section===$key?'active':''?>" href="?section=<?=$key?>"><?=$label?></a><?php endforeach?></nav><div class="user"><b><?=e(admin_user()['name'])?></b><span><?=e(admin_user()['role'])?></span><a href="?logout=1">Sign out</a></div></aside><main class="main"><header><div><span class="eyebrow">SLIID Content Management</span><h1><?=e(ucwords(str_replace('-',' ',$section)))?></h1></div><a class="site-link" href="https://naveen-jayasankha.github.io/sliid-website/" target="_blank" rel="noopener">View website ↗</a></header><?php if($notice):?><div class="notice success"><?=e($notice)?></div><?php endif?><?php if($error):?><div class="notice error"><?=e($error)?></div><?php endif?>
<?php if($section==='dashboard'):$counts=[];foreach(['members','news','events','enquiries','membership_applications'] as $t)$counts[$t]=(int)db()->query("SELECT COUNT(*) FROM $t")->fetchColumn();?><div class="stats"><article><span>Members</span><b><?=$counts['members']?></b></article><article><span>News</span><b><?=$counts['news']?></b></article><article><span>Events</span><b><?=$counts['events']?></b></article><article><span>New enquiries</span><b><?=db()->query("SELECT COUNT(*) FROM enquiries WHERE status='new'")->fetchColumn()?></b></article><article><span>Applications</span><b><?=$counts['membership_applications']?></b></article></div><section class="panel"><h2>Recent activity</h2><table><thead><tr><th>Time</th><th>Action</th><th>Entity</th><th>Administrator</th></tr></thead><tbody><?php foreach(db()->query('SELECT a.*,u.name admin_name FROM audit_logs a LEFT JOIN admins u ON u.id=a.admin_id ORDER BY a.id DESC LIMIT 10')->fetchAll() as $r):?><tr><td><?=e($r['created_at'])?></td><td><?=e($r['action'])?></td><td><?=e($r['entity'])?> #<?=e((string)$r['entity_id'])?></td><td><?=e($r['admin_name']??'System')?></td></tr><?php endforeach?></tbody></table></section>
<?php elseif($section==='members'):$item=record('members',$editId);?><section class="panel"><h2><?=$editId?'Edit member':'Add member'?></h2><form method="post" enctype="multipart/form-data" class="form-grid"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="save_member"><input type="hidden" name="id" value="<?=$editId?>"><label>Name<input name="name" value="<?=e($item['name']??'')?>" required></label><label>Membership number<input name="membership_number" value="<?=e($item['membership_number']??'')?>" required></label><label>Category<select name="category"><?php foreach(['professional','associate','student','industry_partner'] as $v):?><option <?=$v===($item['category']??'')?'selected':''?>><?=$v?></option><?php endforeach?></select></label><label>Status<select name="status"><?php foreach(['active','inactive','pending'] as $v):?><option <?=$v===($item['status']??'active')?'selected':''?>><?=$v?></option><?php endforeach?></select></label><label>Email<input type="email" name="email" value="<?=e($item['email']??'')?>"></label><label>Phone<input name="phone" value="<?=e($item['phone']??'')?>"></label><label>Location<input name="location" value="<?=e($item['location']??'')?>"></label><label>Website<input type="url" name="website" value="<?=e($item['website']??'')?>"></label><label class="full">Specialisations<input name="specialisations" value="<?=e($item['specialisations']??'')?>" placeholder="Residential, Hospitality, Commercial"></label><label class="full">Biography<textarea name="bio" rows="4"><?=e($item['bio']??'')?></textarea></label><label>Profile image<input type="file" name="image" accept="image/jpeg,image/png,image/webp"></label><label class="check"><input type="checkbox" name="featured" <?=!empty($item['featured'])?'checked':''?>> Featured profile</label><button>Save member</button></form></section><?=render_table('members',rows('members','name ASC'),['name'=>'Name','membership_number'=>'Number','category'=>'Category','location'=>'Location','status'=>'Status'])?>
<?php elseif($section==='news'):$item=record('news',$editId);?><section class="panel"><h2><?=$editId?'Edit article':'Add article'?></h2><form method="post" enctype="multipart/form-data" class="form-grid"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="save_news"><input type="hidden" name="id" value="<?=$editId?>"><label class="full">Title<input name="title" value="<?=e($item['title']??'')?>" required></label><label>Slug<input name="slug" value="<?=e($item['slug']??'')?>"></label><label>Category<input name="category" value="<?=e($item['category']??'Institute Update')?>"></label><label>Status<select name="status"><?php foreach(['draft','published','archived'] as $v):?><option <?=$v===($item['status']??'draft')?'selected':''?>><?=$v?></option><?php endforeach?></select></label><label>Publish date<input type="datetime-local" name="published_at" value="<?=!empty($item['published_at'])?e(date('Y-m-d\TH:i',strtotime($item['published_at']))):''?>"></label><label class="full">Excerpt<textarea name="excerpt" rows="3"><?=e($item['excerpt']??'')?></textarea></label><label class="full">Content<textarea name="content" rows="10"><?=e($item['content']??'')?></textarea></label><label>Featured image<input type="file" name="image" accept="image/jpeg,image/png,image/webp"></label><button>Save article</button></form></section><?=render_table('news',rows('news'),['title'=>'Title','category'=>'Category','status'=>'Status','published_at'=>'Published'])?>
<?php elseif($section==='events'):$item=record('events',$editId);?><section class="panel"><h2><?=$editId?'Edit event':'Add event'?></h2><form method="post" enctype="multipart/form-data" class="form-grid"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="save_event"><input type="hidden" name="id" value="<?=$editId?>"><label class="full">Title<input name="title" value="<?=e($item['title']??'')?>" required></label><label>Slug<input name="slug" value="<?=e($item['slug']??'')?>"></label><label>Venue<input name="venue" value="<?=e($item['venue']??'')?>"></label><label>Starts<input type="datetime-local" name="starts_at" value="<?=!empty($item['starts_at'])?e(date('Y-m-d\TH:i',strtotime($item['starts_at']))):''?>" required></label><label>Ends<input type="datetime-local" name="ends_at" value="<?=!empty($item['ends_at'])?e(date('Y-m-d\TH:i',strtotime($item['ends_at']))):''?>"></label><label>Status<select name="status"><?php foreach(['draft','published','cancelled'] as $v):?><option <?=$v===($item['status']??'draft')?'selected':''?>><?=$v?></option><?php endforeach?></select></label><label>Registration URL<input type="url" name="registration_url" value="<?=e($item['registration_url']??'')?>"></label><label class="full">Summary<textarea name="summary" rows="3"><?=e($item['summary']??'')?></textarea></label><label class="full">Description<textarea name="description" rows="8"><?=e($item['description']??'')?></textarea></label><label>Event image<input type="file" name="image" accept="image/jpeg,image/png,image/webp"></label><label class="check"><input type="checkbox" name="featured" <?=!empty($item['featured'])?'checked':''?>> Featured event</label><button>Save event</button></form></section><?=render_table('events',rows('events','starts_at DESC'),['title'=>'Title','venue'=>'Venue','starts_at'=>'Start','status'=>'Status'])?>
<?php elseif($section==='publications'):$item=record('publications',$editId);?><section class="panel"><h2><?=$editId?'Edit publication':'Add publication'?></h2><form method="post" enctype="multipart/form-data" class="form-grid"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="save_publication"><input type="hidden" name="id" value="<?=$editId?>"><label class="full">Title<input name="title" value="<?=e($item['title']??'')?>" required></label><label>Category<input name="category" value="<?=e($item['category']??'Professional Practice')?>" required></label><label>Status<select name="status"><option <?=$item['status']??''==='draft'?'selected':''?>>draft</option><option <?=($item['status']??'')==='published'?'selected':''?>>published</option></select></label><label>Publish date<input type="datetime-local" name="published_at" value="<?=!empty($item['published_at'])?e(date('Y-m-d\TH:i',strtotime($item['published_at']))):''?>"></label><label>External URL<input type="url" name="external_url" value="<?=e($item['external_url']??'')?>"></label><label class="full">Description<textarea name="description" rows="4"><?=e($item['description']??'')?></textarea></label><label>PDF file<input type="file" name="file" accept="application/pdf"></label><button>Save publication</button></form></section><?=render_table('publications',rows('publications'),['title'=>'Title','category'=>'Category','status'=>'Status','published_at'=>'Published'])?>
<?php elseif($section==='enquiries'):?><?=render_status_table('enquiries',rows('enquiries'),['name'=>'Name','email'=>'Email','subject'=>'Subject','message'=>'Message','created_at'=>'Received'],['new','in_progress','resolved','spam'])?>
<?php elseif($section==='applications'):?><?=render_status_table('membership_applications',rows('membership_applications'),['name'=>'Name','email'=>'Email','phone'=>'Phone','category'=>'Category','qualification'=>'Qualification','message'=>'Message','created_at'=>'Received'],['new','reviewing','approved','rejected'])?>
<?php elseif($section==='admins'):?><section class="panel"><h2>Add administrator</h2><?php if(is_super()):?><form method="post" class="form-grid"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="save_admin"><label>Name<input name="name" required></label><label>Email<input type="email" name="email" required></label><label>Password<input type="password" name="password" minlength="12" required></label><label>Role<select name="role"><option value="editor">Editor</option><option value="super_admin">Super administrator</option></select></label><button>Create administrator</button></form><?php else:?><p>Only a super administrator can create accounts.</p><?php endif?></section><?=render_table('admins',rows('admins','name ASC'),['name'=>'Name','email'=>'Email','role'=>'Role','last_login_at'=>'Last login'])?>
<?php elseif($section==='audit'):?><section class="panel"><h2>Audit log</h2><table><thead><tr><th>Date</th><th>Action</th><th>Entity</th><th>Record</th><th>IP</th></tr></thead><tbody><?php foreach(rows('audit_logs') as $r):?><tr><td><?=e($r['created_at'])?></td><td><?=e($r['action'])?></td><td><?=e($r['entity'])?></td><td><?=e((string)$r['entity_id'])?></td><td><?=e($r['ip_address'])?></td></tr><?php endforeach?></tbody></table></section><?php endif?></main></body></html>
<?php
function render_table(string $table,array $records,array $columns):string{ob_start();?><section class="panel list"><h2>Current records</h2><div class="table-wrap"><table><thead><tr><?php foreach($columns as $label):?><th><?=e($label)?></th><?php endforeach?><th>Actions</th></tr></thead><tbody><?php foreach($records as $r):?><tr><?php foreach($columns as $key=>$label):?><td><?=e((string)($r[$key]??''))?></td><?php endforeach?><td class="actions"><a href="?section=<?=$table?>&edit=<?=$r['id']?>">Edit</a><?php if(is_super()):?><form method="post" onsubmit="return confirm('Delete this item?')"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="table" value="<?=e($table)?>"><input type="hidden" name="id" value="<?=$r['id']?>"><button>Delete</button></form><?php endif?></td></tr><?php endforeach?></tbody></table></div></section><?php return ob_get_clean();}
function render_status_table(string $table,array $records,array $columns,array $statuses):string{ob_start();?><section class="panel list"><h2><?=e(ucwords(str_replace('_',' ',$table)))?></h2><div class="table-wrap"><table><thead><tr><?php foreach($columns as $label):?><th><?=e($label)?></th><?php endforeach?><th>Status</th></tr></thead><tbody><?php foreach($records as $r):?><tr><?php foreach($columns as $key=>$label):?><td><?=e((string)($r[$key]??''))?></td><?php endforeach?><td><form method="post" class="status-form"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="set_status"><input type="hidden" name="table" value="<?=e($table)?>"><input type="hidden" name="id" value="<?=$r['id']?>"><select name="status" onchange="this.form.submit()"><?php foreach($statuses as $s):?><option <?=$s===$r['status']?'selected':''?>><?=$s?></option><?php endforeach?></select></form></td></tr><?php endforeach?></tbody></table></div></section><?php return ob_get_clean();}
